// AUTO-GENERATED by scripts/gen_pi_extension.py — do not edit by hand.
// Regenerates the radarAnalyze capability registry into pi registerTool blocks.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { execFileSync } from "node:child_process";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";

const pythonExecutable = process.env.CR60_RADAR_ANALYZE_PYTHON ?? "python";

// 项目根：本扩展位于 <root>/.pi/extensions/，从文件路径向上两级。
function projectRoot() {
  const extensionDir = dirname(fileURLToPath(import.meta.url));
  return dirname(dirname(extensionDir));
}

export default function (pi: ExtensionAPI) {
  pi.registerTool({
    name: "detect_time_pattern",
    description: "Run the deterministic Temporal Pattern Engine on recorded data",
    parameters: {"type": "object", "properties": {"func_name": {"type": "string", "description": "Optional ADAS function filter."}, "extra_patterns": {"type": "array", "items": {"type": "object"}}, "state_transitions": {"type": "array", "items": {"type": "object"}}, "time_window": {"type": "array", "items": {"type": "number"}, "minItems": 2, "maxItems": 2}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "detect_time_pattern", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "plot_signal",
    description: "Describe a requested signal plot and optionally preview points",
    parameters: {"type": "object", "properties": {"message_name": {"type": "string"}, "signal_name": {"type": "string"}, "topic": {"type": "string"}, "field": {"type": "string"}, "time_window": {"type": "array", "items": {"type": "number"}, "minItems": 2, "maxItems": 2}, "preview_limit": {"type": "integer", "minimum": 1, "default": 20}, "output_path": {"type": "string"}, "title": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "plot_signal", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "query_can_data",
    description: "Query recorded CAN/bag-derived data summaries via DataProbe",
    parameters: {"type": "object", "properties": {"field": {"type": "string", "description": "Column name or arithmetic expression."}, "table": {"type": "string", "enum": ["radar_objects", "radar_debug", "warning_events"], "default": "radar_objects"}, "group_by": {"type": "string"}, "filter": {"type": "string"}, "stats": {"oneOf": [{"type": "string"}, {"type": "array", "items": {"type": "string"}}]}, "max_rows": {"type": "integer", "minimum": 1, "default": 500000}}, "required": ["field"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "query_can_data", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "trace-requirement",
    description: "Build deterministic requirement-to-code traceability",
    parameters: {"type": "object", "properties": {"req_id": {"type": "string"}, "spec": {"type": ["object", "null"]}, "req_set": {"type": ["object", "null"]}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "trace-requirement", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "alert-timeline",
    description: "将原始、回放、运行态、GDB 和 CAN 证据投影为可比较报警时间线",
    parameters: {"type": "object", "properties": {"bundle": {"type": "object"}, "bundle_path": {"type": "string"}, "viewer_model": {"type": "object"}, "viewer_model_path": {"type": "string"}, "runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "selected_event": {"type": "object"}, "event_id": {"type": "string"}, "function": {"type": "string"}, "side": {"type": "string"}, "radar_id": {"type": ["string", "integer"]}, "frame_id": {"type": ["string", "integer"]}, "max_rows": {"type": "integer", "default": 240}, "output": {"type": "string"}}, "anyOf": [{"required": ["bundle"]}, {"required": ["bundle_path"]}, {"required": ["viewer_model"]}, {"required": ["viewer_model_path"]}, {"required": ["selected_event"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "alert-timeline", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-claim-append",
    description: "Append one evidence-bound engineering Claim to an AnalysisRun",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "run_id": {"type": "string"}, "step_id": {"type": "string"}, "claim_id": {"type": "string"}, "scope": {"type": "string"}, "statement": {"type": "string"}, "status": {"type": "string", "enum": ["observed", "derived", "inferred", "contradicted", "not_available"]}, "created_by": {"type": "string", "enum": ["tool", "ai", "user"]}, "evidence_refs": {"type": "array", "items": {}}, "assumptions": {"type": "array", "items": {}}, "conflicts": {"type": "array", "items": {}}, "binding": {"type": "object"}}, "required": ["run_id", "scope", "statement", "status", "created_by"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-claim-append", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-hypothesis-record",
    description: "Create or update one evidence-bound root-cause hypothesis",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "hypothesis_id": {"type": "string"}, "category": {"type": "string"}, "statement": {"type": "string"}, "status": {"type": "string", "enum": ["", "open", "testing", "supported", "weakened", "rejected", "confirmed_by_user"]}, "rank": {"type": ["integer", "null"]}, "confidence_band": {"type": "string", "enum": ["", "low", "medium", "high", "unknown"]}, "supporting_claim_refs": {"type": "array", "items": {}}, "contradicting_claim_refs": {"type": "array", "items": {}}, "required_evidence": {"type": "array", "items": {}}, "experiment_refs": {"type": "array", "items": {}}, "binding": {"type": "object"}, "reason": {"type": "string"}, "actor": {"type": "string", "enum": ["tool", "ai", "user", "pi"]}, "run_id": {"type": "string"}}, "required": ["run_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-hypothesis-record", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-run-create",
    description: "Create one durable AnalysisRun for progressive evidence and debug work",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "run_id": {"type": "string"}, "owner": {"type": "string"}, "goal": {"type": "object"}, "question": {"type": "string"}, "customer_claim": {"type": "string"}, "expected": {"type": "string"}, "binding": {"type": "object"}, "policy": {"type": "object"}, "artifact_refs": {"type": "array", "items": {}}}, "anyOf": [{"required": ["goal"]}, {"required": ["question"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-run-create", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-run-read",
    description: "Read one AnalysisRun summary and optionally its durable entities",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "run_id": {"type": "string"}, "include_entities": {"type": "boolean"}}, "required": ["run_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-run-read", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-run-update",
    description: "Update AnalysisRun status, stage, and explicit run metrics",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "run_id": {"type": "string"}, "status": {"type": "string", "enum": ["created", "running", "partial", "blocked", "failed", "completed"]}, "current_stage": {"type": "string"}, "metrics": {"type": "object"}, "metric_mode": {"type": "string", "enum": ["merge", "increment"]}, "actor": {"type": "string"}, "binding": {"type": "object"}, "artifact_refs": {"type": "array", "items": {}}}, "required": ["run_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-run-update", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-step-record",
    description: "Begin or complete one visible AnalysisStep in an AnalysisRun",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "action": {"type": "string", "enum": ["begin", "complete"]}, "run_id": {"type": "string"}, "step_id": {"type": "string"}, "stage": {"type": "string"}, "status": {"type": "string", "enum": ["completed", "partial", "blocked", "failed", "skipped"]}, "created_by": {"type": "string"}, "actor": {"type": "string"}, "input_artifact_refs": {"type": "array", "items": {}}, "output_artifact_refs": {"type": "array", "items": {}}, "tool_calls": {"type": "array", "items": {}}, "observations": {"type": "array", "items": {}}, "gaps": {"type": "array", "items": {}}, "conflicts": {"type": "array", "items": {}}, "user_visible_summary": {"type": "string"}, "next_action_candidates": {"type": "array", "items": {}}, "metrics": {"type": "object"}}, "required": ["action", "run_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-step-record", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "analysis-user-observation",
    description: "Append a user's manual VSCode/GDB/screenshot/note observation",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "run_id": {"type": "string"}, "observation_id": {"type": "string"}, "kind": {"type": "string", "enum": ["manual_vscode", "gdb_transcript", "screenshot", "note"]}, "summary": {"type": "string"}, "content": {"type": "string"}, "artifact_refs": {"type": "array", "items": {}}, "target": {"type": "object"}, "experiment_id": {"type": "string"}, "hypothesis_refs": {"type": "array", "items": {}}, "binding": {"type": "object"}}, "required": ["run_id", "summary"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "analysis-user-observation", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-build",
    description: "Build an explicit arbe workspace with catkin_make",
    parameters: {"type": "object", "properties": {"arbe_root": {"type": "string"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "ros_setup": {"type": "string"}, "catkin_make_args": {"type": "array", "items": {"type": "string"}}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["arbe_root"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-build", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-cuda-resolve",
    description: "Read-only resolve current arbe vehicle CUDA workbook and YAML alignment",
    parameters: {"type": "object", "properties": {"intake": {"type": "object"}, "intake_path": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "arbe_root": {"type": "string"}, "algo_source_root": {"type": "string"}, "vehicle": {"type": "string"}, "coem": {"type": "string"}, "cuda_sheet": {"type": "string"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "config_dir": {"type": "string"}, "config_name": {"type": "string"}, "execute": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-cuda-resolve", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-formal-start",
    description: "Start formal arbe bash start with an owned auditable session",
    parameters: {"type": "object", "properties": {"harness_root": {"type": "string"}, "profile": {"type": "string"}, "ros_master_uri": {"type": "string"}, "start_path": {"type": "string"}, "ready_timeout_sec": {"type": "number"}, "clean_remote_log": {"type": "boolean"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "python_executable": {"type": "string"}, "timeout_sec": {"type": "number"}, "session_output": {"type": "string"}, "output": {"type": "string"}}, "required": ["harness_root", "profile"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-formal-start", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-formal-stop",
    description: "Stop only a tool-owned formal arbe start session",
    parameters: {"type": "object", "properties": {"harness_root": {"type": "string"}, "profile": {"type": "string"}, "session_path": {"type": "string"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "python_executable": {"type": "string"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["harness_root", "profile", "session_path"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-formal-stop", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-patch-plan",
    description: "Read-only inspect configurable arbe simulation adaptation checks and dirty diffs",
    parameters: {"type": "object", "properties": {"intake": {"type": "object"}, "intake_path": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "arbe_root": {"type": "string"}, "algo_source_root": {"type": "string"}, "checks": {"type": "array", "items": {"type": "object"}}, "include_diff": {"type": "boolean"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "execute": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-patch-plan", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-preflight",
    description: "Read-only probe of arbe/source/config/binary/GDB/runtime readiness",
    parameters: {"type": "object", "properties": {"server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "arbe_root": {"type": "string"}, "algo_source_root": {"type": "string"}, "ros_setup": {"type": "string"}, "ros_master_uri": {"type": "string"}, "timeout_sec": {"type": "number"}, "include_process_snapshot": {"type": "boolean"}, "output": {"type": "string"}}, "required": ["arbe_root"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-preflight", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "arbe-source-resolve",
    description: "Read-only resolve current algo_source branch/tag and configured version mapping",
    parameters: {"type": "object", "properties": {"intake": {"type": "object"}, "intake_path": {"type": "string"}, "arbe_root": {"type": "string"}, "algo_source_root": {"type": "string"}, "requested_ref": {"type": "string"}, "software_version": {"type": "string"}, "ref_prefix": {"type": "string"}, "version_suffix_strip": {"type": "string"}, "remote_name": {"type": "string"}, "remote_query": {"type": "boolean"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "execute": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "arbe-source-resolve", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "bsd-data-bridge",
    description: "BSD signal matching + condition cross-validation (M9)",
    parameters: {"type": "object", "properties": {"mode": {"type": "string"}, "mf4_path": {"type": "string"}, "case_dir": {"type": "string"}, "source_root": {"type": "string"}, "output_dir": {"type": "string"}}, "additionalProperties": true, "required": ["mode"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "bsd-data-bridge", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-analyze",
    description: "代码分析：调用链 / 依赖 / 语义（基于 CodeGraph）",
    parameters: {"type": "object", "properties": {"kind": {"type": "string", "enum": ["function", "callers", "callees", "call_chain", "signals_of", "vars_read", "vars_written", "calib", "conditions", "stats"]}, "name": {"type": "string"}, "signal": {"type": "string"}, "max_depth": {"type": "integer"}, "db_path": {"type": "string"}, "source_root": {"type": "string"}, "code_index_path": {"type": "string"}, "code_index": {"type": "object"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-analyze", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-context-read",
    description: "读取已建立 Code Context 的指定代码关系或摘要",
    parameters: {"type": "object", "properties": {"context_path": {"type": "string"}, "section": {"type": "string", "enum": ["summary", "files", "functions", "calls", "variables_read", "call_chain", "variables_written", "signals", "output_mapping", "conditions", "states", "parameters", "semantics", "edges"]}, "query": {"type": "string"}, "limit": {"type": "integer"}}, "required": ["context_path"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-context-read", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-context-refresh",
    description: "一次性建立当前源码的确定性 Code Context Snapshot",
    parameters: {"type": "object", "properties": {"source_root": {"type": "string"}, "output_dir": {"type": "string"}, "db_path": {"type": "string"}, "key_files": {"type": "array", "items": {"type": "string"}}, "calib_files": {"type": "array", "items": {"type": "string"}}, "function_keywords": {"type": "object"}, "source_identity": {"type": "object"}, "source_docs_dir": {"type": "string"}, "probe_git": {"type": "boolean"}, "use_ast": {"type": "boolean"}, "no_ast": {"type": "boolean"}, "force": {"type": "boolean"}, "max_files": {"type": "integer"}}, "required": ["source_root"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-context-refresh", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-gdb-plan",
    description: "Analyze current code index and generate generic source-bound GDB instructions",
    parameters: {"type": "object", "properties": {"code_index_path": {"type": "string"}, "code_index": {"type": "object"}, "function_name": {"type": "string"}, "source_file": {"type": "string"}, "line": {"type": "integer"}, "condition": {"type": "string"}, "frame_scope": {"type": "object"}, "object_scope": {"type": "object"}, "watch_variables": {"type": "array", "items": {"type": "string"}}, "auto_continue": {"type": "boolean"}, "backtrace_depth": {"type": "integer"}, "source_root": {"type": "string"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-gdb-plan", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-learn",
    description: "代码学习：AST 建图 / 增量刷新 CodeGraph（P5 入口）",
    parameters: {"type": "object", "properties": {"rebuild": {"type": "boolean", "default": false}, "use_ast": {"type": "boolean", "default": true}, "aggressive": {"type": "boolean", "default": false}, "no_ast": {"type": "boolean", "default": false}, "source_root": {"type": "string", "default": ""}, "db_path": {"type": "string", "default": ""}}, "additionalProperties": true},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-learn", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "code-review",
    description: "Offline deterministic code review with safety/syntax hooks (M7)",
    parameters: {"type": "object", "properties": {"diff_text": {"type": "string", "default": ""}, "diff_file": {"type": "string"}, "file_path": {"type": "string"}, "file_paths": {"type": "array"}, "syntax_check": {"type": "boolean"}, "no_syntax_check": {"type": "boolean", "default": false}, "syntax_tool": {"type": "string"}}, "additionalProperties": true},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "code-review", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "condition-trace",
    description: "按当前源码条件和同帧真实字段生成条件证据",
    parameters: {"type": "object", "properties": {"conditions": {"type": ["array", "object"]}, "values": {"type": "object"}, "parameters": {"type": ["array", "object"]}, "event_id": {"type": "string"}, "function": {"type": "string"}, "frame_id": {}, "source_root": {"type": "string"}, "max_conditions": {"type": "integer", "default": 80}, "output": {"type": "string"}}, "required": ["conditions"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "condition-trace", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "cr60-data-prep-verify",
    description: "Read-only verify CR60 data files, size and SHA-256 before/after transfer",
    parameters: {"type": "object", "properties": {"intake": {"type": "object"}, "intake_path": {"type": "string"}, "data_paths": {"type": "array", "items": {"type": "string"}}, "destination_root": {"type": "string"}, "source_prefix": {"type": "string"}, "extensions": {"type": "array", "items": {"type": "string"}}, "check_destination": {"type": "boolean"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "execute": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "cr60-data-prep-verify", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "cr60-data-transfer",
    description: "Run the configured bosch-data-transfert script after explicit approval",
    parameters: {"type": "object", "properties": {"server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "identity_file": {"type": "string"}, "script_path": {"type": "string"}, "input_path": {"type": "string"}, "destination_root": {"type": "string"}, "source_type": {"type": "string", "enum": ["xlsx", "list"]}, "source_prefix": {"type": "string"}, "python_executable": {"type": "string"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["script_path", "input_path", "destination_root"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "cr60-data-transfer", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "cr60-intake",
    description: "Read CR60 materials and explicit inputs; resolve data/software/vehicle/COEM candidates without guessing",
    parameters: {"type": "object", "properties": {"data_paths": {"type": "array", "items": {"type": "string"}}, "material_paths": {"type": "array", "items": {"type": "string"}}, "match_text": {"type": "array", "items": {"type": "string"}}, "software_version": {"type": "string"}, "vehicle": {"type": "string"}, "customer": {"type": "string"}, "coem": {"type": "string"}, "code_branch": {"type": "string"}, "ticket_id": {"type": "string"}, "function": {"type": "array", "items": {"type": "string"}}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "arbe_root": {"type": "string"}, "algo_source_root": {"type": "string"}, "code_root": {"type": "string"}, "dbc": {"type": "string"}, "cuda_sheet": {"type": "string"}, "customer_claim": {"type": "string"}, "preferred_radar": {}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "cr60-intake", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "cr60-precheck",
    description: "Delegate deterministic CR60 Sprint1 folder/handoff analysis to the independent cr60-debug-harness",
    parameters: {"type": "object", "properties": {"mode": {"enum": ["folder", "handoff", "manifest"]}, "harness_root": {"type": "string"}, "profile": {"type": "string"}, "input_dir": {"type": "string"}, "intake_path": {"type": "string"}, "manifest_path": {"type": "string"}, "output_dir": {"type": "string"}, "context": {"type": "string"}, "prepare_context": {"type": "boolean"}, "max_source_files": {"type": "integer"}, "functions": {"type": "array", "items": {"type": "string"}}, "customer_claim": {"type": "string"}, "web_dist": {"type": "string"}, "allow_partial": {"type": "boolean"}, "execute": {"type": "boolean"}, "python_executable": {"type": "string"}, "timeout_sec": {"type": "number"}}, "required": ["mode", "harness_root", "profile", "output_dir"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "cr60-precheck", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "data-explore",
    description: "Probe & summarize vehicle data without code (M4)",
    parameters: {"type": "object", "properties": {"field": {"type": "string"}, "table": {"type": "string", "default": "radar_objects"}, "group_by": {"type": "string"}, "filter": {"type": "string"}, "stats": {"type": "array"}, "case_dir": {"type": "string"}}, "additionalProperties": true, "required": ["field"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "data-explore", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "debug-experiment-record",
    description: "Plan or record one bounded debug experiment in an AnalysisRun",
    parameters: {"type": "object", "properties": {"ledger_root": {"type": "string"}, "action": {"type": "string", "enum": ["plan", "update"]}, "run_id": {"type": "string"}, "experiment_id": {"type": "string"}, "question": {"type": "string"}, "method": {"type": "string", "enum": ["", "static_query", "public_runtime", "replay", "gdb", "manual_vscode", "parameter_what_if"]}, "status": {"type": "string", "enum": ["", "planned", "approval_required", "running", "completed", "partial", "blocked", "failed"]}, "target": {"type": "object"}, "plan_ref": {"type": ["object", "null"]}, "approval": {"type": "object"}, "session_ref": {"type": ["object", "null"]}, "watch_groups": {"type": "array", "items": {}}, "expected_discrimination": {"type": "array", "items": {}}, "observations": {"type": "array", "items": {}}, "disturbance": {"type": "object"}, "conclusion_delta": {"type": "array", "items": {}}, "hypothesis_refs": {"type": "array", "items": {}}, "binding": {"type": "object"}, "reason": {"type": "string"}, "actor": {"type": "string", "enum": ["tool", "ai", "user", "pi"]}}, "required": ["action", "run_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "debug-experiment-record", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "diagnosis-panel",
    description: "Classify a diagnosis request and optionally run the panel (M6)",
    parameters: {"type": "object", "properties": {"problem": {"type": "string"}, "expected": {"type": "string", "default": ""}, "mode": {"type": "string", "default": "auto"}, "func_name": {"type": "string", "default": ""}, "data_summary": {"type": "string", "default": ""}, "memory_context": {"type": "string", "default": ""}, "fail_type": {"type": "string", "default": "OTHER"}, "task_type": {"type": "string", "default": ""}}, "additionalProperties": true, "required": ["problem"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "diagnosis-panel", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "diagnosis-report",
    description: "生成单事件或全数据的证据绑定详细诊断报告",
    parameters: {"type": "object", "properties": {"bundle": {"type": "object"}, "bundle_path": {"type": "string"}, "viewer_model": {"type": "object"}, "viewer_model_path": {"type": "string"}, "runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "runtime_debug_plan": {"type": "object"}, "runtime_debug_plan_path": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "code_context": {"type": "object"}, "code_context_path": {"type": "string"}, "event_code_path": {"type": "object"}, "event_code_path_path": {"type": "string"}, "condition_trace": {"type": "object"}, "condition_trace_path": {"type": "string"}, "gdb_session": {"type": "object"}, "gdb_session_path": {"type": "string"}, "analysis": {"type": "object"}, "analysis_run": {"type": "object"}, "analysis_run_path": {"type": "string"}, "event_id": {"type": "string"}, "event_index": {"type": "integer"}, "function": {"type": "string"}, "side": {"type": "string"}, "radar_id": {"type": ["string", "integer"]}, "frame_id": {"type": ["string", "integer"]}, "output_endpoint": {"type": "string", "enum": ["auto", "algorithm", "can_tx"], "default": "algorithm"}, "can_data_status": {"type": "string", "enum": ["present", "absent", "not_detected", "unknown"]}, "max_events": {"type": "integer", "default": 100}, "max_frames": {"type": "integer", "default": 24}, "max_targets": {"type": "integer", "default": 24}, "output_dir": {"type": "string"}, "response_mode": {"type": "string", "enum": ["summary", "full"], "default": "summary"}}, "anyOf": [{"required": ["bundle"]}, {"required": ["bundle_path"]}, {"required": ["viewer_model"]}, {"required": ["viewer_model_path"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "diagnosis-report", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "event-code-path",
    description: "将事件绑定到当前源码函数、调用链、条件、变量和 GDB 计划",
    parameters: {"type": "object", "properties": {"event": {"type": "object"}, "code_index_path": {"type": "string"}, "context_path": {"type": "string"}, "source_root": {"type": "string"}, "max_call_depth": {"type": "integer"}, "max_breakpoints": {"type": "integer"}, "output": {"type": "string"}}, "required": ["event"], "anyOf": [{"required": ["code_index_path"]}, {"required": ["context_path"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "event-code-path", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "evidence-query",
    description: "按事件、帧、功能和字段查询已有 CR60 证据 artifact",
    parameters: {"type": "object", "properties": {"bundle": {"type": "object"}, "bundle_path": {"type": "string"}, "viewer_model": {"type": "object"}, "viewer_model_path": {"type": "string"}, "runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "event_id": {"type": "string"}, "event_index": {"type": "integer"}, "function": {"type": "string", "description": "功能/事件函数 token；精确匹配，也允许 token_侧别 前缀匹配"}, "side": {"type": "string"}, "radar_id": {"type": ["string", "integer"]}, "frame_id": {"type": ["string", "integer"]}, "fields": {"type": "array", "items": {"type": "string"}, "description": "真实 artifact 点号字段路径，例如 target.fields、ego.fields、frame、code.call_chain"}, "max_events": {"type": "integer", "default": 20}, "max_frames": {"type": "integer", "default": 24}, "max_targets": {"type": "integer", "default": 24}, "include_details": {"type": "boolean", "default": false}, "max_field_rows": {"type": "integer", "default": 32}, "output": {"type": "string", "description": "可选输出文件路径；仅在用户明确要求落盘且给出路径时传入，不要填写 json/text 等格式名"}}, "anyOf": [{"required": ["bundle"]}, {"required": ["bundle_path"]}, {"required": ["viewer_model"]}, {"required": ["viewer_model_path"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "evidence-query", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "gdb-service",
    description: "Generic headless GDB attach/inspect service; no feature-specific breakpoints",
    parameters: {"type": "object", "properties": {"target": {"type": "object"}, "commands": {"type": "array", "items": {"type": "string"}}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["target", "commands"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "gdb-service", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "memory-recall",
    description: "读取当前项目/功能/案例的历史记忆和相似案例",
    parameters: {"type": "object", "properties": {"project_root": {"type": "string"}, "function": {"type": "string"}, "query": {"type": "string"}, "case_dir": {"type": "string"}, "variant_id": {"type": "string"}, "memory_dir": {"type": "string"}, "context": {"type": "object"}, "context_path": {"type": "string"}, "layers": {"type": ["array", "string"], "items": {"type": "string"}}, "max_items": {"type": "integer", "default": 5}, "max_chars": {"type": "integer", "default": 6000}, "output": {"type": "string"}}, "required": ["project_root"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "memory-recall", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "pi-context",
    description: "Build an immutable provenance-bound Pi orchestration context",
    parameters: {"type": "object", "properties": {"intake": {"type": "object"}, "intake_path": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "case_dir": {"type": "string"}, "project_root": {"type": "string"}, "project_id": {"type": "string"}, "variant_id": {"type": "string"}, "operator": {"type": "string"}, "run_id": {"type": "string"}, "replay_strategy": {"type": "string"}, "radar_id": {"type": "string"}, "freshness": {"type": "object"}, "policy": {"type": "object"}, "artifact_refs": {"type": "array", "items": {"type": "object"}}, "runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "diagnosis_bundle": {"type": "object"}, "diagnosis_bundle_path": {"type": "string"}, "runtime_debug_plan": {"type": "object"}, "runtime_debug_plan_path": {"type": "string"}, "capability_manifest": {"type": "object"}, "capability_manifest_path": {"type": "string"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "pi-context", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "project-capability-manifest",
    description: "生成当前项目/源码/数据的能力清单与缺口声明",
    parameters: {"type": "object", "properties": {"identity": {"type": "object"}, "project_id": {"type": "string"}, "variant_id": {"type": "string"}, "intake": {"type": "object"}, "intake_path": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "code_context": {"type": "object"}, "code_context_path": {"type": "string"}, "runtime_snapshot": {"type": "object"}, "runtime_snapshot_path": {"type": "string"}, "diagnosis_bundle": {"type": "object"}, "diagnosis_bundle_path": {"type": "string"}, "declared_capabilities": {"type": "object"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "project-capability-manifest", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "project-init",
    description: "Bootstrap config.local.yaml and a variant-scoped workspace sandbox",
    parameters: {"type": "object", "properties": {"name": {"type": "string"}, "code_root": {"type": "string"}, "dbcs": {"type": "array"}, "customer": {"type": "string"}, "vehicle_project": {"type": "string"}, "coem_project": {"type": "string"}, "requirements": {"type": "array"}, "expected_branch": {"type": "string", "default": "master"}, "case_dir": {"type": "string"}, "platform": {"type": "string", "default": "gen6_c_radar"}, "variant": {"type": "string"}, "output": {"type": "string", "default": "config.local.yaml"}, "dry_run": {"type": "boolean", "default": false}, "no_set_default": {"type": "boolean", "default": false}, "branch": {"type": "string"}}, "additionalProperties": true, "required": ["name", "code_root"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "project-init", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "public-evidence-audit",
    description: "Audit per-frame ego/object/warning evidence available without GDB",
    parameters: {"type": "object", "properties": {"bundle_path": {"type": "string"}, "output": {"type": "string"}}, "required": ["bundle_path"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "public-evidence-audit", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "public-runtime-normalize",
    description: "归一化 arbe 公共运行时报警、自车和目标属性快照",
    parameters: {"type": "object", "properties": {"capture_path": {"type": "string"}, "warning_rows": {"type": "array", "items": {"type": "object"}}, "radar_info_rows": {"type": "array", "items": {"type": "object"}}, "object_rows": {"type": "array", "items": {"type": "object"}}, "source_context": {"type": "object"}, "warning_names": {"type": "array", "items": {"type": "string"}}, "object_association_mode": {"type": "string", "enum": ["auto", "publication_order", "strict"]}, "object_validity_policy": {"type": "string", "enum": ["arbe_wf_sobj", "preserve"]}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "runtime_schema_path": {"type": "string"}, "output": {"type": "string"}}, "anyOf": [{"required": ["capture_path"]}, {"required": ["warning_rows"]}, {"required": ["radar_info_rows"]}, {"required": ["object_rows"]}], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "public-runtime-normalize", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "public-topic-plan",
    description: "Plan public arbe ROS/bag evidence channels that do not require GDB",
    parameters: {"type": "object", "properties": {"profile_path": {"type": "string"}, "preflight_path": {"type": "string"}, "runtime_schema_path": {"type": "string"}, "topic_inventory_path": {"type": "string"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "public-topic-plan", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "req-analyze",
    description: "需求→代码 gap 分析（violations + requirement_trace，复用 code-analyze）",
    parameters: {"type": "object", "properties": {"req_dir": {"type": "string", "default": ""}, "variant_id": {"type": "string", "default": ""}, "max_trace": {"type": "integer", "default": 5}, "variant": {"type": "string", "default": ""}, "db_path": {"type": "string", "default": ""}}, "additionalProperties": true},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "req-analyze", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "ros-topic-inventory",
    description: "Read-only ROS topic type/publisher/subscriber inventory for an arbe runtime",
    parameters: {"type": "object", "properties": {"topics": {"type": "array", "items": {"type": "string"}}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "ros_setup": {"type": "string"}, "workspace_setup": {"type": "string"}, "timeout_sec": {"type": "number"}, "execute": {"type": "boolean"}, "sample_once": {"type": "boolean"}, "sample_timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["topics"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "ros-topic-inventory", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-debug-attach",
    description: "Attach an approved source-bound GDB plan to an existing formal arbe PID",
    parameters: {"type": "object", "properties": {"harness_root": {"type": "string"}, "profile": {"type": "string"}, "bag": {"type": "string"}, "debug_plan_path": {"type": "string"}, "target_frame": {"type": "integer"}, "radar_id": {"type": "integer"}, "start_sec": {"type": "number"}, "duration_sec": {"type": "number"}, "node_pattern": {"type": "string"}, "topic": {"type": "string"}, "ros_master_uri": {"type": "string"}, "replay": {"type": "boolean"}, "wait_sec": {"type": "number"}, "keep_remote_logs": {"type": "boolean"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "python_executable": {"type": "string"}, "timeout_sec": {"type": "number"}, "session_output": {"type": "string"}, "output": {"type": "string"}}, "required": ["harness_root", "profile", "bag", "debug_plan_path", "target_frame", "radar_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-debug-attach", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-debug-plan",
    description: "Build a source/data-bound replay and GDB readiness plan from one alarm event",
    parameters: {"type": "object", "properties": {"bundle": {"type": "object"}, "bundle_path": {"type": "string"}, "event_id": {"type": "string"}, "event_index": {"type": "integer"}, "runtime_mode": {"type": "string"}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "event_code_path": {"type": "object"}, "event_code_path_path": {"type": "string"}, "source_context": {"type": "object"}, "binary_context": {"type": "object"}, "permissions": {"type": "object"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-debug-plan", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-debug-run",
    description: "Run one approved isolated ROS/GDB session from runtime-debug-plan.v1",
    parameters: {"type": "object", "properties": {"harness_root": {"type": "string"}, "profile": {"type": "string"}, "bag": {"type": "string"}, "debug_plan_path": {"type": "string"}, "target_frame": {"type": "integer"}, "radar_id": {"type": "integer"}, "master_port": {"type": "integer"}, "start_sec": {"type": "number"}, "duration_sec": {"type": "number"}, "session_output": {"type": "string"}, "keep_remote_logs": {"type": "boolean"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "python_executable": {"type": "string"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "required": ["harness_root", "profile", "bag", "debug_plan_path", "target_frame", "radar_id"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-debug-run", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-evidence-compose",
    description: "Compose public runtime and headless GDB evidence without dropping producer history",
    parameters: {"type": "object", "properties": {"left": {"type": "object"}, "left_path": {"type": "string"}, "right": {"type": "object"}, "right_path": {"type": "string"}, "output": {"type": "string"}}, "required": ["output"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-evidence-compose", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-evidence-merge",
    description: "Bind runtime evidence to a diagnosis bundle and emit additive runtime overlay",
    parameters: {"type": "object", "properties": {"bundle": {"type": "object"}, "bundle_path": {"type": "string"}, "runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "scope": {"type": "object"}, "output": {"type": "string"}}, "required": ["output"], "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-evidence-merge", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-evidence-normalize",
    description: "Normalize headless GDB or public arbe runtime facts into runtime-case-evidence.v1",
    parameters: {"type": "object", "properties": {"gdb_session": {"type": "object"}, "gdb_session_path": {"type": "string"}, "public_runtime_snapshot": {"type": "object"}, "public_runtime_snapshot_path": {"type": "string"}, "public_warning_names": {"type": "array", "items": {"type": "string"}}, "transcript": {"type": "string"}, "transcript_path": {"type": "string"}, "stderr": {"type": "string"}, "commands": {"type": "array", "items": {"type": "string"}}, "run": {"type": "object"}, "binding": {"type": "object"}, "marker_field_map": {"type": "object"}, "artifacts": {"type": "object"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-evidence-normalize", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "runtime-evidence-validate",
    description: "Validate runtime-case-evidence identity and event binding without changing artifacts",
    parameters: {"type": "object", "properties": {"runtime_evidence": {"type": "object"}, "runtime_evidence_path": {"type": "string"}, "bundle": {"type": "object"}, "bundle_path": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "runtime-evidence-validate", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "signal-audit",
    description: "Extract and audit key CAN signals from a BLF (enum validity + contract)",
    parameters: {"type": "object", "properties": {"mode": {"type": "string"}, "signals": {"type": "string", "default": ""}, "blf_path": {"type": "string"}, "dbc": {"type": "array", "items": {"type": "string"}, "default": []}}, "additionalProperties": true, "required": ["mode"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "signal-audit", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "signal-bridge",
    description: "Resolve CAN/internal signal mappings without recorded data (M2)",
    parameters: {"type": "object", "properties": {"mode": {"type": "string"}, "query": {"type": "string", "default": ""}, "func_name": {"type": "string", "default": ""}, "source_root": {"type": "string"}, "output_dir": {"type": "string"}, "knowledge_dir": {"type": "string"}, "rte_file": {"type": "string", "default": "coem\\GWM_B26\\components\\AswIf\\ASW_IN\\RteComMapping.c"}}, "additionalProperties": true, "required": ["mode"]},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "signal-bridge", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "signal-extract",
    description: "信号抽取 + 绘图：模糊匹配 CAN / 雷达内部信号并输出时间线/曲线",
    parameters: {"type": "object", "properties": {"query": {"type": "string", "default": ""}, "case_dir": {"type": "string", "default": ""}, "plot": {"type": "boolean", "default": true}, "write_csv": {"type": "boolean", "default": true}, "no_plot": {"type": "boolean", "default": false}}, "additionalProperties": true},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "signal-extract", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
  pi.registerTool({
    name: "sim-verify",
    description: "仿真验证：解析 arbe 回放产生的 warning trace / KPI",
    parameters: {"type": "object", "properties": {"mode": {"type": "string", "enum": ["local", "remote_public"]}, "case_dir": {"type": "string"}, "output_dir": {"type": "string"}, "server_host": {"type": "string"}, "server_user": {"type": "string"}, "server_port": {"type": "integer"}, "remote_bag_path": {"type": "string"}, "remote_capture_base": {"type": "string"}, "local_capture_path": {"type": "string"}, "input_topics": {"type": "array", "items": {"type": "string"}}, "output_topics": {"type": "array", "items": {"type": "string"}}, "ros_setup": {"type": "string"}, "workspace_setup": {"type": "string"}, "ros_master_uri": {"type": "string"}, "start_sec": {"type": "number"}, "duration_sec": {"type": "number"}, "warning_names": {"type": "array", "items": {"type": "string"}}, "object_association_mode": {"type": "string", "enum": ["auto", "strict", "publication_order"]}, "object_validity_policy": {"type": "string", "enum": ["preserve", "arbe_wf_sobj"]}, "preflight": {"type": "object"}, "preflight_path": {"type": "string"}, "source_context": {"type": "object"}, "execute": {"type": "boolean"}, "approved": {"type": "boolean"}, "timeout_sec": {"type": "number"}, "output": {"type": "string"}}, "additionalProperties": false},
    async execute(toolCallId, params, signal, onUpdate, ctx) {
      const out = JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", "--name", "sim-verify", "--params", JSON.stringify(params ?? {})], { cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString());
      return { content: [{ type: "text", text: JSON.stringify(out) }], details: out };
    },
  });
}
