# -*- coding: utf-8 -*-
"""
Tests for Phase 15 / 2.1 — knowledge-injection efficiency.

Covers three sub-tasks:

* 2.1.1  ``--prewarm`` CLI option and ``_run_prewarm()`` summary metadata
* 2.1.2  ``signal_mapper.trace_variable_chains()`` SHA256 incremental cache
* 2.1.3  ``Orchestrator.__init__`` pre-loads signal maps for downstream reuse

These tests are offline (no LLM, no real BAG/BLF). They build minimal
mock source trees via ``tmp_path`` and exercise the deterministic paths.

Run with::

    pytest tests/test_phase15_prewarm.py -v

from ``D:\\RamboStar\\idea\\radarAnalyze``.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


# ─────────────────────────────────────────────────────────────────────────
# Helpers: build a mock source tree that mimics the parts
# ``trace_variable_chains`` cares about (RteComMapping.c + globalVariDef*.c).
# ─────────────────────────────────────────────────────────────────────────

_RTE_COM_MAPPING = """\
// Auto-generated by RTE — do not edit
#include "Rte.h"
(void)RteComMapping_ReadSignal(CarSpd)(&carSpd);
(void)RteComMapping_ReadSignal(YawRate)(&yawRate);
(void)RteComMapping_WriteSignal(OutRadarInfo)(&g_outRadarInfo);
(void)RteComMapping_WriteSignal(OutBsdLWarning)(&g_outBsdLWarning);
"""

_GLOBAL_VAR_DEF = """\
// globalVariDef.c — struct copies
#include "globalVarDefine.h"

void CopyRadarInputs(const RteRadarIn_t *param) {
    g_radarDistX = *param;
}

void CopyEgoInfo(const RteEgoInfo_t *info) {
    g_egoCarSpd = info;
}
"""


def _write_source_tree(source_root: Path) -> Path:
    """Create a minimal mock source tree and return source_root."""
    rte_dir = source_root / "coem" / "GWM_B26" / "components" / "AswIf" / "ASW_IN"
    rte_dir.mkdir(parents=True, exist_ok=True)
    (rte_dir / "RteComMapping.c").write_text(_RTE_COM_MAPPING, encoding="utf-8")

    gv_dir = source_root / "coem" / "GWM_B26" / "components" / "AswPerception" / "func"
    gv_dir.mkdir(parents=True, exist_ok=True)
    (gv_dir / "globalVariDef.c").write_text(_GLOBAL_VAR_DEF, encoding="utf-8")

    return source_root


# ─────────────────────────────────────────────────────────────────────────
# 2.1.2: trace_variable_chains SHA256 incremental cache
# ─────────────────────────────────────────────────────────────────────────

def test_trace_variable_chains_writes_meta_cache(tmp_path: Path) -> None:
    """First call writes both variable_chains.json and variable_chains.meta.json."""
    from engines.signal_mapper import trace_variable_chains

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs"

    result = trace_variable_chains(source_root, docs_dir)
    assert "struct_aliases" in result

    cache_path = docs_dir / "variable_chains.json"
    meta_path = docs_dir / "variable_chains.meta.json"
    assert cache_path.exists(), "variable_chains.json should be written"
    assert meta_path.exists(), "variable_chains.meta.json should be written"

    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    assert "file_hashes" in meta
    assert meta.get("version") == 1
    assert meta.get("alias_count") == len(result.get("struct_aliases", {}))
    assert meta.get("rte_file", "").endswith("RteComMapping.c")
    # Every scanned source file should have a hash entry.
    assert len(meta["file_hashes"]) >= 1


def test_trace_variable_chains_cache_hit_on_unchanged(tmp_path: Path) -> None:
    """Second call with unchanged source files returns cached result (no rescan)."""
    from ai import signal_mapper

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs"

    # First call — full scan + write
    first = signal_mapper.trace_variable_chains(source_root, docs_dir)
    first_meta = json.loads(
        (docs_dir / "variable_chains.meta.json").read_text(encoding="utf-8")
    )

    # Patch _extract_rte_write_prefixes to detect if rescan runs.
    call_count = {"n": 0}
    real_extract = signal_mapper._extract_rte_write_prefixes

    def counted(rte_path):
        call_count["n"] += 1
        return real_extract(rte_path)

    signal_mapper._extract_rte_write_prefixes = counted
    try:
        second = signal_mapper.trace_variable_chains(source_root, docs_dir)
    finally:
        signal_mapper._extract_rte_write_prefixes = real_extract

    # Cache hit → should NOT have called _extract_rte_write_prefixes (file is unchanged).
    assert call_count["n"] == 0, "Cache hit should skip file reads"
    assert second == first, "Cached result should match the original"

    # Meta should be unchanged (same file hashes).
    second_meta = json.loads(
        (docs_dir / "variable_chains.meta.json").read_text(encoding="utf-8")
    )
    assert second_meta["file_hashes"] == first_meta["file_hashes"]


def test_trace_variable_chains_invalidation_on_change(tmp_path: Path) -> None:
    """Changing a scanned source file invalidates the cache and triggers rescan."""
    from ai import signal_mapper

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs"

    signal_mapper.trace_variable_chains(source_root, docs_dir)
    first_meta = json.loads(
        (docs_dir / "variable_chains.meta.json").read_text(encoding="utf-8")
    )

    # Mutate one of the scanned files
    gv_file = (
        source_root / "coem" / "GWM_B26" / "components" / "AswPerception" / "func"
        / "globalVariDef.c"
    )
    gv_file.write_text(_GLOBAL_VAR_DEF + "\n// extra line\n", encoding="utf-8")

    # Second call should detect hash mismatch and rescan
    call_count = {"n": 0}
    real_extract = signal_mapper._extract_rte_write_prefixes

    def counted(rte_path):
        call_count["n"] += 1
        return real_extract(rte_path)

    signal_mapper._extract_rte_write_prefixes = counted
    try:
        signal_mapper.trace_variable_chains(source_root, docs_dir)
    finally:
        signal_mapper._extract_rte_write_prefixes = real_extract

    assert call_count["n"] >= 1, "File change should trigger a rescan"

    second_meta = json.loads(
        (docs_dir / "variable_chains.meta.json").read_text(encoding="utf-8")
    )
    # The hash for the modified file MUST change.
    gv_rel = (
        "coem\\GWM_B26\\components\\AswPerception\\func\\globalVariDef.c"
    )
    assert second_meta["file_hashes"][gv_rel] != first_meta["file_hashes"][gv_rel]


def test_trace_variable_chains_force_bypasses_cache(tmp_path: Path) -> None:
    """``force=True`` bypasses the cache and always rescans."""
    from ai import signal_mapper

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs"

    signal_mapper.trace_variable_chains(source_root, docs_dir)

    call_count = {"n": 0}
    real_extract = signal_mapper._extract_rte_write_prefixes

    def counted(rte_path):
        call_count["n"] += 1
        return real_extract(rte_path)

    signal_mapper._extract_rte_write_prefixes = counted
    try:
        signal_mapper.trace_variable_chains(source_root, docs_dir, force=True)
    finally:
        signal_mapper._extract_rte_write_prefixes = real_extract

    assert call_count["n"] >= 1, "force=True should trigger a rescan"


def test_trace_variable_chains_corrupt_meta_falls_through(tmp_path: Path) -> None:
    """Corrupted meta.json is treated as cache miss (fall through to full scan)."""
    from engines.signal_mapper import trace_variable_chains

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs"

    trace_variable_chains(source_root, docs_dir)
    # Corrupt the meta file
    (docs_dir / "variable_chains.meta.json").write_text(
        "{not valid json", encoding="utf-8"
    )
    # Should NOT raise; should rescan and rewrite meta
    result = trace_variable_chains(source_root, docs_dir)
    assert "struct_aliases" in result
    meta = json.loads(
        (docs_dir / "variable_chains.meta.json").read_text(encoding="utf-8")
    )
    assert "file_hashes" in meta  # rewritten


# ─────────────────────────────────────────────────────────────────────────
# 2.1.3: Orchestrator pre-loads signal maps
# ─────────────────────────────────────────────────────────────────────────

def test_orchestrator_preloads_signal_maps(tmp_path: Path) -> None:
    """Orchestrator.__init__ should populate signal_mapping / variable_chains / output_signal_mapping."""
    from ai.orchestrator import Orchestrator

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs" / "gen6_gwm_b26"
    docs_dir.mkdir(parents=True, exist_ok=True)

    config = {
        "paths": {
            "source_code": str(source_root),
            "source_docs": str(docs_dir),
        },
        "project": {"source_docs_dir": str(docs_dir)},
    }

    orch = Orchestrator(config, tmp_path)
    # Pre-load should populate all three signal maps.
    assert isinstance(orch.signal_mapping, dict)
    assert isinstance(orch.variable_chains, dict)
    assert isinstance(orch.output_signal_mapping, dict)
    # trace_variable_chains was called → cache files exist.
    assert (docs_dir / "variable_chains.json").exists()
    assert (docs_dir / "variable_chains.meta.json").exists()


def test_orchestrator_signal_map_fallback_on_load_failure(tmp_path: Path) -> None:
    """If pre-load fails, signal maps remain empty (sub-methods fall back)."""
    from ai.orchestrator import Orchestrator

    # Invalid config: source_root doesn't exist → trace_variable_chains returns empty
    config = {
        "paths": {
            "source_code": str(tmp_path / "nonexistent"),
            "source_docs": str(tmp_path / "docs"),
        },
        "project": {"source_docs_dir": str(tmp_path / "docs")},
    }
    orch = Orchestrator(config, tmp_path)
    # Even on failure, attributes should exist as dicts (possibly empty)
    assert isinstance(orch.signal_mapping, dict)
    assert isinstance(orch.variable_chains, dict)
    assert isinstance(orch.output_signal_mapping, dict)


# ─────────────────────────────────────────────────────────────────────────
# 2.1.1: --prewarm CLI + _run_prewarm summary
# ─────────────────────────────────────────────────────────────────────────

def test_run_prewarm_writes_meta_json(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """``_run_prewarm`` writes ``prewarm_meta.json`` containing elapsed_sec + ops."""
    # Patch CodeLearner at its source module (cli imports it lazily inside _run_prewarm).
    import ai.code_learner as _cl_mod

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs" / "gen6_gwm_b26"
    docs_dir.mkdir(parents=True, exist_ok=True)

    config = {
        "paths": {
            "source_code": str(source_root),
            "source_docs": str(docs_dir),
        },
        "project": {"source_docs_dir": str(docs_dir)},
        "identity": {"variant_id": "gen6/gwm_b26"},
    }

    class _StubRouter:
        pass

    monkeypatch.setattr("cli.get_router", lambda cfg: _StubRouter())

    class _StubLearner:
        def __init__(self, router, cfg, root):
            pass

        def learn(self, status_cb=None, force_pairs=None, force_constants=False):
            return {"learned_count": 0, "skipped_count": 0, "error_count": 0}

        def ensure_overview_docs(self, funcs=None, force=False, status_cb=None):
            return {"generated": [], "skipped": list(funcs or []), "failed": [],
                    "reason": "all_up_to_date"}

    monkeypatch.setattr(_cl_mod, "CodeLearner", _StubLearner)

    from cli import _run_prewarm
    summary = _run_prewarm(config=config, force=False)

    meta_path = docs_dir / "prewarm_meta.json"
    assert meta_path.exists(), "prewarm_meta.json should be written"
    meta = json.loads(meta_path.read_text(encoding="utf-8"))
    assert "operations" in meta
    assert "elapsed_sec" in meta
    assert meta["force"] is False
    # trace_variable_chains was actually called → variable_chains.json exists
    assert (docs_dir / "variable_chains.json").exists()


def test_run_prewarm_force_rebuilds_caches(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """``force=True`` should mark the summary as forced and call trace_variable_chains(force=True)."""
    import ai.code_learner as _cl_mod

    source_root = _write_source_tree(tmp_path / "src")
    docs_dir = tmp_path / "source_docs" / "gen6_gwm_b26"
    docs_dir.mkdir(parents=True, exist_ok=True)

    config = {
        "paths": {
            "source_code": str(source_root),
            "source_docs": str(docs_dir),
        },
        "project": {"source_docs_dir": str(docs_dir)},
        "identity": {"variant_id": "gen6/gwm_b26"},
    }

    class _StubRouter:
        pass

    monkeypatch.setattr("cli.get_router", lambda cfg: _StubRouter())

    class _StubLearner:
        def __init__(self, router, cfg, root):
            pass

        def learn(self, status_cb=None, force_pairs=None, force_constants=False):
            return {"learned_count": 0, "skipped_count": 0, "error_count": 0}

        def ensure_overview_docs(self, funcs=None, force=False, status_cb=None):
            return {"generated": [], "skipped": list(funcs or []), "failed": [],
                    "reason": "forced_rebuild"}

    monkeypatch.setattr(_cl_mod, "CodeLearner", _StubLearner)

    from cli import _run_prewarm
    summary = _run_prewarm(config=config, force=True)
    assert summary["force"] is True
    assert "operations" in summary
    # variable_chains was rebuilt under force=True
    assert "variable_chains" in summary["operations"]


if __name__ == "__main__":
    import sys
    import io
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    else:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8",
                                       errors="replace", line_buffering=True)
    raise SystemExit(pytest.main([__file__, "-v"]))