# -*- coding: utf-8 -*-
"""P0 · 从能力清单生成 pi 扩展 TS（registerTool 块）。

对应 V4_PI_BASED_PLAN.md Slice P0：``python scripts/gen_pi_extension.py`` 生成
含全部已注册能力（BaseTool 工具 + BaseModule 模块）的扩展 TS。字段单一来源取自
:func:`ai.capability.registry.capability_catalog()`（D-PI-6：能力三件套）。

生成物是自包含单文件 TS 扩展（默认 ``.pi/extensions/radar-capabilities.ts``）：

* **所有业务能力** → execute 经 ``python -m ai.capability.pi_tool_bridge`` 调用；
  bridge 再统一分派到现有 BaseTool 或 BaseModule adapter。

用法::

    python scripts/gen_pi_extension.py [--out .pi/extensions/radar-capabilities.ts]
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import tempfile
from pathlib import Path

# 让 `python scripts/gen_pi_extension.py` 可从项目根导入 ai / engines
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


HEADER = (
    "// AUTO-GENERATED by scripts/gen_pi_extension.py — do not edit by hand.\n"
    '// Regenerates the radarAnalyze capability registry into pi registerTool blocks.\n'
    'import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";\n'
    'import { execFileSync } from "node:child_process";\n'
    'import { dirname } from "node:path";\n'
    'import { fileURLToPath } from "node:url";\n\n'
    'const pythonExecutable = process.env.CR60_RADAR_ANALYZE_PYTHON ?? "python";\n\n'
    '// 项目根：本扩展位于 <root>/.pi/extensions/，从文件路径向上两级。\n'
    'function projectRoot() {\n'
    '  const extensionDir = dirname(fileURLToPath(import.meta.url));\n'
    '  return dirname(dirname(extensionDir));\n'
    '}\n\n'
    "export default function (pi: ExtensionAPI) {\n"
)

FOOTER = "}\n"

#: 所有能力走同一个 JSON bridge。params 必须作为独立 argv 传入，不能拼接
#: shell 字符串，避免空参数、引号和路径空格导致 Pi tool 实际丢参。
_BRIDGE_CALL_TMPL = (
    'JSON.parse(execFileSync(pythonExecutable, ["-m", "ai.capability.pi_tool_bridge", '
    '"--name", "NAME", "--params", JSON.stringify(params ?? {})], '
    '{ cwd: projectRoot(), encoding: "utf8", maxBuffer: 16 * 1024 * 1024 }).toString())'
)


def _js(value) -> str:
    """Python 值 → JS 字面量。"""
    return json.dumps(value, ensure_ascii=False)


def _tool_block(cap: dict) -> str:
    name = cap["name"]
    desc = cap.get("description") or ""
    params = cap.get("parameters") or {"type": "object", "properties": {}}
    call = _BRIDGE_CALL_TMPL.replace("NAME", name)
    return (
        f"  pi.registerTool({{\n"
        f"    name: {_js(name)},\n"
        f"    description: {_js(desc)},\n"
        f"    parameters: {_js(params)},\n"
        f"    async execute(toolCallId, params, signal, onUpdate, ctx) {{\n"
        f"      const out = {call};\n"
        f"      return {{ content: [{{ type: \"text\", text: JSON.stringify(out) }}], "
        f"details: out }};\n"
        f"    }},\n"
        f"  }});\n"
    )


def generate(catalog) -> str:
    """按 module → tool 顺序生成完整扩展 TS。

    编排根（pi/AgentLoop/ReAct）和 ask_user 不注册为业务 Pi tool，避免
    递归或把 Pi 自己的交互协议暴露成普通后端工具。重复名称也只保留一项。
    """
    excluded = {"pi", "agent-repl", "agent-loop", "ask_user"}
    ordered = sorted(catalog, key=lambda c: (c.get("kind") != "tool", c["name"]))
    filtered = []
    seen: set[str] = set()
    for cap in ordered:
        name = str(cap.get("name", ""))
        if not name or name in excluded or not cap.get("expose_to_pi", True) or name in seen:
            continue
        seen.add(name)
        filtered.append(cap)
    body = "".join(_tool_block(c) for c in filtered)
    return HEADER + body + FOOTER


def main(argv=None) -> int:
    # The generator is often launched by Pi/Node with stdout redirected to a
    # pipe.  Keep the diagnostic line UTF-8-safe on Windows cp1252 consoles so
    # a successful generation is not reported as a failed subprocess.
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, OSError):
            pass
    p = argparse.ArgumentParser(description="生成 pi extension registerTool 块")
    p.add_argument("--out", default=".pi/extensions/radar-capabilities.ts",
                   help="输出 TS 路径")
    p.add_argument("--modules-only", action="store_true", help="仅生成 module 能力")
    p.add_argument("--tools-only", action="store_true", help="仅生成 tool 能力")
    args = p.parse_args(argv)

    from ai.capability.registry import capability_catalog
    catalog = capability_catalog()
    include_modules = not args.tools_only
    include_tools = not args.modules_only
    filtered = [
        c for c in catalog
        if (include_modules and c["kind"] == "module")
        or (include_tools and c["kind"] == "tool")
    ]
    ts = generate(filtered)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    # Atomic replacement prevents concurrent Pi sessions from observing a
    # partially-written extension when the catalog is refreshed on startup.
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=str(out.parent),
        prefix=f".{out.name}.", suffix=".tmp", delete=False,
    ) as handle:
        temporary = Path(handle.name)
        handle.write(ts)
    try:
        os.replace(temporary, out)
    finally:
        try:
            temporary.unlink(missing_ok=True)
        except OSError:
            pass
    visible_names = [
        c["name"] for c in filtered
        if c.get("expose_to_pi", True)
        and c["name"] not in {"pi", "agent-repl", "agent-loop", "ask_user"}
    ]
    n_mod = sum(1 for c in filtered if c["kind"] == "module" and c["name"] in visible_names)
    n_tool = sum(1 for c in filtered if c["kind"] == "tool" and c["name"] in visible_names)
    print(f"[OK] 生成 {out}: {len(visible_names)} Pi 能力（{n_mod} 模块 + {n_tool} 工具）")
    print(f"     首个: {visible_names[0] if visible_names else '-'} / "
          f"末个: {visible_names[-1] if visible_names else '-'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
