# -*- coding: utf-8 -*-
"""Deterministic CR60/arbe environment and runtime preflight.

This module deliberately performs read-only discovery only. It does not
checkout branches, change configuration, compile, start ROS, attach GDB, or
stop processes. The public result is an auditable arbe-preflight.v1 payload
which later runtime/build providers can consume.

The command runner is intentionally injected. Production uses an allowlisted
SSH runner; tests use a fake runner. No Pi/LLM text is executed as a shell
command by this module.
"""
from __future__ import annotations

import re
import shlex
import subprocess
import time
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any, Mapping, Protocol


SCHEMA_VERSION = "arbe-preflight.v1"
DEFAULT_ARBE_RELATIVE_ALGO = "src/algo_source"
DEFAULT_CONFIG_RELATIVE = (
    "src/arbe_phoenix_radar_driver-master/arbe_gui/Config/"
    "launch_config_4radars.yaml"
)
DEFAULT_VIS_LAUNCH_RELATIVE = (
    "src/arbe_phoenix_radar_driver-master/arbe_gui/launch/arbe_radar_vis.launch"
)
DEFAULT_PARA_DEFINE_RELATIVE = (
    "src/algo_source/adas/symmetry/perception/include/paraDefine.h"
)

_READONLY_SCAN_PATTERN = (
    "RteComMapping_TxRunnable_FuncSignal|"
    "RteComMapping_WriteSignal|"
    "RteLite_Write_|"
    "Com_SendSignal|"
    "ADAS_Core_Process"
)

# Member-path assignment scanning is deliberately source-generic.  It is used
# after the Tx candidates are found to answer a narrower question than "what
# signal names exist?": where is the internal value used by a selected
# WriteSignal actually assigned in the active source snapshot?  The scan is a
# navigation/evidence aid only; it never claims that the assignment executed.
_MEMBER_ASSIGNMENT_PATTERN = (
    r"([A-Za-z_][A-Za-z0-9_]*(?:->|\.)[A-Za-z_][A-Za-z0-9_]*)"
    r"[[:space:]]*(=|\+=|-=|\*=|/=|%=)"
)
_MEMBER_PATH_RE = re.compile(
    r"\b[A-Za-z_][A-Za-z0-9_]*(?:(?:->|\.)[A-Za-z_][A-Za-z0-9_]*)+"
)


def _member_assignment_pattern(tokens: set[str]) -> str:
    """Build a narrow POSIX-ERE pattern for the discovered output members."""
    if not tokens:
        return _MEMBER_ASSIGNMENT_PATTERN
    return "|".join(
        f"{re.escape(token)}[[:space:]]*(=|\\+=|-=|\\*=|/=|%=)"
        for token in sorted(tokens, key=len, reverse=True)
    )


@dataclass(frozen=True)
class CommandResult:
    """Captured result of one read-only command."""

    command: str
    returncode: int
    stdout: str = ""
    stderr: str = ""
    timed_out: bool = False
    duration_sec: float = 0.0

    @property
    def ok(self) -> bool:
        return self.returncode == 0 and not self.timed_out

    def to_dict(self) -> dict[str, Any]:
        return {
            "command": self.command,
            "returncode": self.returncode,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "timed_out": self.timed_out,
            "duration_sec": round(self.duration_sec, 6),
            "ok": self.ok,
        }


class CommandRunner(Protocol):
    """Internal runner contract; commands are generated by ArbePreflight."""

    def run(self, command: str, *, timeout_sec: float) -> CommandResult:
        ...


class LocalShellRunner:
    """Run a generated read-only command on the local POSIX host."""

    def run(self, command: str, *, timeout_sec: float) -> CommandResult:
        started = time.monotonic()
        try:
            completed = subprocess.run(
                ["bash", "-lc", command],
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=max(0.1, float(timeout_sec)),
                check=False,
            )
            return CommandResult(
                command=command,
                returncode=completed.returncode,
                stdout=completed.stdout,
                stderr=completed.stderr,
                duration_sec=time.monotonic() - started,
            )
        except subprocess.TimeoutExpired as exc:
            return CommandResult(
                command=command,
                returncode=124,
                stdout=_as_text(exc.stdout),
                stderr=_as_text(exc.stderr),
                timed_out=True,
                duration_sec=time.monotonic() - started,
            )
        except OSError as exc:
            return CommandResult(
                command=command,
                returncode=127,
                stderr=f"{type(exc).__name__}: {exc}",
                duration_sec=time.monotonic() - started,
            )


class SshCommandRunner:
    """Run generated commands through an explicit SSH argument list.

    ArbePreflight is the only intended caller. The runner receives
    already-generated read-only commands; it does not expand user-supplied
    shell fragments.
    """

    def __init__(
        self,
        *,
        host: str,
        username: str = "",
        port: int = 22,
        identity_file: str = "",
        ssh_binary: str = "ssh",
    ) -> None:
        self.host = str(host).strip()
        self.username = str(username).strip()
        self.port = int(port)
        self.identity_file = str(identity_file).strip()
        self.ssh_binary = ssh_binary

    @property
    def destination(self) -> str:
        return f"{self.username}@{self.host}" if self.username else self.host

    def run(self, command: str, *, timeout_sec: float) -> CommandResult:
        started = time.monotonic()
        args = [
            self.ssh_binary,
            "-o",
            "BatchMode=yes",
            "-o",
            f"ConnectTimeout={max(1, int(min(timeout_sec, 60.0)))}",
            "-p",
            str(self.port),
        ]
        if self.identity_file:
            args.extend(["-i", self.identity_file])
        # OpenSSH concatenates all arguments after the destination into the
        # remote command.  Passing bash/-lc/command as three separate args
        # makes bash receive only the first word as its command string.  Keep
        # the shell command as one quoted remote argument instead.
        remote_command = "bash -lc " + shlex.quote(command)
        args.extend([self.destination, remote_command])
        display = " ".join(shlex.quote(item) for item in args)
        try:
            completed = subprocess.run(
                args,
                capture_output=True,
                text=True,
                encoding="utf-8",
                errors="replace",
                timeout=max(0.1, float(timeout_sec)),
                check=False,
            )
            return CommandResult(
                command=display,
                returncode=completed.returncode,
                stdout=completed.stdout,
                stderr=completed.stderr,
                duration_sec=time.monotonic() - started,
            )
        except subprocess.TimeoutExpired as exc:
            return CommandResult(
                command=display,
                returncode=124,
                stdout=_as_text(exc.stdout),
                stderr=_as_text(exc.stderr),
                timed_out=True,
                duration_sec=time.monotonic() - started,
            )
        except OSError as exc:
            return CommandResult(
                command=display,
                returncode=127,
                stderr=f"{type(exc).__name__}: {exc}",
                duration_sec=time.monotonic() - started,
            )


def _as_text(value: object) -> str:
    if value is None:
        return ""
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace")
    return str(value)


def _q(value: str) -> str:
    return shlex.quote(str(value))


def _join_remote(root: str, relative: str) -> str:
    return str(PurePosixPath(root.rstrip("/")) / relative.lstrip("/"))


def _parse_macro_values(text: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for match in re.finditer(
        # The remote probe uses grep -n, so a line may be either
        # ``#define ...`` or ``123:#define ...``.  Keep the parser tolerant
        # of that transport decoration while still parsing only C macros.
        r"^(?:[0-9]+:)?[ \t]*#define[ \t]+"
        r"([A-Za-z_][A-Za-z0-9_]*)[ \t]+([^/\r\n]+)",
        text,
        flags=re.MULTILINE,
    ):
        result[match.group(1)] = match.group(2).strip()
    return result


def _parse_config_values(text: str) -> dict[str, Any]:
    """Extract stable scalar/list values without assuming a fixed YAML parser."""

    values: dict[str, Any] = {}
    scalar_patterns = {
        "coem_name": r"(?m)^[ \t]*type:[ \t]*([A-Za-z0-9_.-]+)[ \t]*$",
        "xlsx_path": r"(?m)^[ \t]*xlsx_path:[ \t]*[\"']?([^\"'\r\n]+)[\"']?[ \t]*$",
        "xlsx_sheet": r"(?m)^[ \t]*xlsx_sheet:[ \t]*[\"']?([^\"'\r\n]+)[\"']?[ \t]*$",
        "n_radars": r"(?m)^[ \t]*n_radars:[ \t]*([0-9]+)[ \t]*$",
        "enable_gui": r"(?m)^[ \t]*enable_gui:[ \t]*([A-Za-z0-9_.-]+)[ \t]*$",
    }
    for key, pattern in scalar_patterns.items():
        match = re.search(pattern, text)
        if match:
            values[key] = match.group(1).strip()

    list_patterns = {
        "radar_ids": r"(?m)^[ \t]*radar_id:[ \t]*\[([^\]]*)\]",
        "radar_pos": r"(?m)^[ \t]*radar_pos:[ \t]*\[([^\]]*)\]",
        "orientation": r"(?m)^[ \t]*orientation:[ \t]*\[([^\]]*)\]",
        "yaw_in_degrees": r"(?m)^[ \t]*yaw_in_degrees:[ \t]*\[([^\]]*)\]",
        "radar_x_offset": r"(?m)^[ \t]*radar_x_offset:[ \t]*\[([^\]]*)\]",
        "radar_y_offset": r"(?m)^[ \t]*radar_y_offset:[ \t]*\[([^\]]*)\]",
    }
    for key, pattern in list_patterns.items():
        match = re.search(pattern, text)
        if not match:
            continue
        raw_items = [item.strip() for item in match.group(1).split(",")]
        values[key] = [item for item in raw_items if item]

    return values


def _radar_id_from_namespace(namespace: str) -> int | None:
    match = re.fullmatch(r"radar([0-9]+)_visualization_engine", namespace or "")
    return int(match.group(1)) if match else None


def _parse_processes(text: str) -> list[dict[str, Any]]:
    processes: list[dict[str, Any]] = []
    for line in text.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        match = re.match(r"^\s*(\d+)\s+(.*)$", stripped)
        if not match:
            continue
        pid = int(match.group(1))
        command = match.group(2).strip()
        namespace = ""
        ns_match = re.search(
            r"/(radar\d+_visualization_engine)/arbe_visualization_engine",
            command,
        )
        if ns_match is None:
            ns_match = re.search(
                r"(?:__ns|__name):=/(radar\d+_visualization_engine)",
                command,
            )
        if ns_match:
            namespace = ns_match.group(1)
        # In the current arbe launch, ``ps -eo args`` may not expose the ROS
        # namespace.  The launch wrapper does, however, place the namespace in
        # the rosout log filename, e.g. ``radar2_visualization_engine-...``.
        # This is a discovery fallback, not a semantic claim about the
        # algorithm's radar coordinate mapping.
        if not namespace:
            log_match = re.search(
                r"(?:^|/)(radar\d+)_visualization_engine-",
                command,
            )
            if log_match:
                namespace = f"{log_match.group(1)}_visualization_engine"
        if not namespace:
            generic_match = re.search(
                r"\b(radar\d+)_visualization_engine\b",
                command,
            )
            if generic_match:
                namespace = f"{generic_match.group(1)}_visualization_engine"
        processes.append(
            {
                "pid": pid,
                "command": command,
                "namespace": namespace,
                "radar_id": _radar_id_from_namespace(namespace),
                "executable": "arbe_visualization_engine"
                if "arbe_visualization_engine" in command
                else "",
            }
        )
    return processes


def _parse_source_refs(text: str) -> list[dict[str, Any]]:
    refs: list[dict[str, Any]] = []
    for line in text.splitlines():
        match = re.match(r"^(.*?):([0-9]+):(.*)$", line)
        if not match:
            continue
        path, line_no, snippet = match.groups()
        refs.append(
            {
                "path": path,
                "line": int(line_no),
                "snippet": snippet.strip(),
            }
        )
    return refs


def _parse_signal_tokens(text: str) -> list[str]:
    tokens: set[str] = set()
    lines = []
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        snippet = location.group(3) if location else raw
        if snippet.lstrip().startswith(("//", "/*", "*")):
            continue
        lines.append(snippet)
    active_text = "\n".join(lines)
    for pattern in (
        r"RteComMapping_WriteSignal\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)",
        r"\bRteLite_Write_([A-Za-z_][A-Za-z0-9_]*)\b",
    ):
        tokens.update(match.group(1) for match in re.finditer(pattern, active_text))
    return sorted(tokens)


def _parse_signal_mappings(text: str) -> list[dict[str, Any]]:
    """Parse active source-side Tx calls from grep output.

    The result is intentionally a source mapping, not a runtime claim.  The
    caller may use it to show the current signal expression or to build a
    source-bound GDB plan, but it must still be compared with a runtime/CAN
    observation before calling the signal transmitted.
    """
    write_re = re.compile(
        r"RteComMapping_WriteSignal\(\s*([A-Za-z_][A-Za-z0-9_]*)\s*\)\s*\((.*)\)\s*;"
    )
    mappings: list[dict[str, Any]] = []
    seen: set[tuple[str, str, int]] = set()
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        if not location:
            continue
        path, line_text, snippet = location.groups()
        if snippet.lstrip().startswith(("//", "/*", "*")):
            continue
        match = write_re.search(snippet)
        if not match:
            continue
        signal, expression = match.groups()
        try:
            line_number = int(line_text)
        except ValueError:
            continue
        key = (path, signal, line_number)
        if key in seen:
            continue
        seen.add(key)
        mappings.append({
            "signal": signal,
            "expression": expression.strip(),
            "source_ref": {"path": path, "line": line_number},
            "snippet": snippet.strip(),
            "source_kind": "source_rte_tx_mapping",
        })
    return mappings


def _parse_transport_mappings(text: str) -> list[dict[str, Any]]:
    """Pair RteLite writer functions with their Com_SendSignal call.

    This is a source navigation aid, not a runtime/CAN observation.  The
    active source may use a different generated transport API, so rows are
    emitted only when both a writer token and a nearby send call are visible
    in the same source file.
    """
    writer_re = re.compile(r"\bRteLite_Write_([A-Za-z_][A-Za-z0-9_]*)\s*\(")
    can_signal_re = re.compile(
        r"ComConf_ComSignal_S_(.+?)_Can_Network_Channel_[A-Za-z0-9_]+"
    )
    rows: list[dict[str, Any]] = []
    pending: dict[str, Any] | None = None
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        if not location:
            continue
        path, line_text, snippet = location.groups()
        if snippet.lstrip().startswith(("//", "/*", "*")):
            continue
        try:
            line_number = int(line_text)
        except ValueError:
            continue
        writer = writer_re.search(snippet)
        if writer:
            pending = {
                "signal": writer.group(1),
                "rte_lite_function": f"RteLite_Write_{writer.group(1)}",
                "source_ref": {"path": path, "line": line_number},
                "writer_snippet": snippet.strip(),
            }
            continue
        if pending is None:
            continue
        if path != pending["source_ref"]["path"] or line_number - int(pending["source_ref"]["line"]) > 40:
            pending = None
            continue
        send = re.search(r"\bCom_SendSignal\b", snippet)
        if not send:
            continue
        can_signal = can_signal_re.search(snippet)
        row = {
            **pending,
            "com_send_source_ref": {"path": path, "line": line_number},
            "com_signal": can_signal.group(1) if can_signal else "",
            "send_snippet": snippet.strip(),
            "source_kind": "source_rte_lite_to_com_send",
        }
        rows.append(row)
        pending = None
    return rows


def _extract_member_paths(expression: str) -> list[str]:
    """Return real C/C++ member paths referenced by a source expression."""
    seen: set[str] = set()
    result: list[str] = []
    for match in _MEMBER_PATH_RE.finditer(str(expression or "")):
        token = match.group(0)
        if token not in seen:
            seen.add(token)
            result.append(token)
    return result


def _extract_function_calls(expression: str) -> list[str]:
    """Return callable identifiers from a source-side assignment expression."""
    keywords = {"if", "for", "while", "switch", "sizeof", "return"}
    seen: set[str] = set()
    result: list[str] = []
    for match in re.finditer(r"\b([A-Za-z_][A-Za-z0-9_]*)\s*\(", str(expression or "")):
        name = match.group(1)
        if name in keywords or name in seen:
            continue
        seen.add(name)
        result.append(name)
    return result


def _parse_function_refs(text: str, *, names: set[str]) -> list[dict[str, Any]]:
    """Parse source locations that mention discovered producer functions."""
    if not names:
        return []
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, int, str]] = set()
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        if not location:
            continue
        path, line_text, snippet = location.groups()
        try:
            line_number = int(line_text)
        except ValueError:
            continue
        for name in sorted(names, key=len, reverse=True):
            if not re.search(rf"\b{re.escape(name)}\s*\(", snippet):
                continue
            key = (path, line_number, name)
            if key in seen:
                continue
            seen.add(key)
            stripped = snippet.lstrip()
            rows.append({
                "name": name,
                "source_ref": {"path": path, "line": line_number},
                "snippet": snippet.strip(),
                "active": not stripped.startswith(("//", "/*", "*")),
            })
    return rows


def _parse_member_assignments(
    text: str,
    *,
    selected_tokens: set[str],
) -> list[dict[str, Any]]:
    """Parse member assignments from a bounded remote grep result.

    The parser keeps commented lines because they are important evidence when
    an output mapping is disabled in the current source.  ``active`` is only
    a lexical source classification; it is not a runtime execution claim.
    """
    if not selected_tokens:
        return []
    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, int, str, str]] = set()
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        if not location:
            continue
        path, line_text, snippet = location.groups()
        try:
            line_number = int(line_text)
        except ValueError:
            continue
        stripped = snippet.lstrip()
        active = not stripped.startswith(("//", "/*", "*"))
        for token in sorted(selected_tokens, key=len, reverse=True):
            match = re.search(
                rf"{re.escape(token)}\s*(\+=|-=|\*=|/=|%=|=(?!=))\s*(.*?)(?:;|$)",
                snippet,
            )
            if not match:
                continue
            operator, rhs = match.groups()
            key = (path, line_number, token, operator)
            if key in seen:
                continue
            seen.add(key)
            rows.append({
                "token": token,
                "operator": operator,
                "rhs": rhs.strip(),
                "source_ref": {"path": path, "line": line_number},
                "snippet": snippet.strip(),
                "active": active,
                "status": "source_active" if active else "source_commented",
                "input_member_paths": _extract_member_paths(rhs),
            })
    return rows


def _build_source_output_chain(
    mappings: list[dict[str, Any]],
    assignments: list[dict[str, Any]],
    *,
    function_refs: list[dict[str, Any]] | None = None,
    probe: Mapping[str, Any],
) -> dict[str, Any]:
    """Join Tx expressions to their source-side internal assignments."""
    by_token: dict[str, list[dict[str, Any]]] = {}
    for row in assignments:
        token = str(row.get("token") or "").strip()
        if token:
            by_token.setdefault(token, []).append(dict(row))
    by_function: dict[str, list[dict[str, Any]]] = {}
    for row in function_refs or []:
        name = str(row.get("name") or "").strip()
        if name:
            by_function.setdefault(name, []).append(dict(row))
    rows: list[dict[str, Any]] = []
    for mapping in mappings:
        signal = str(mapping.get("signal") or "").strip()
        expression = str(mapping.get("expression") or "").strip()
        if not signal:
            continue
        internal_paths = _extract_member_paths(expression)
        matching = [
            assignment
            for token in internal_paths
            for assignment in by_token.get(token, [])
        ]
        active = [item for item in matching if item.get("active") is True]
        primary_assignment = next(
            (
                item for item in active
                if _extract_function_calls(str(item.get("rhs") or ""))
            ),
            active[0] if active else None,
        )
        producer_functions = [
            name
            for assignment in active
            for name in _extract_function_calls(str(assignment.get("rhs") or ""))
        ]
        producer_function_refs = [
            item
            for name in dict.fromkeys(producer_functions)
            for item in by_function.get(name, [])
        ]
        if active:
            assignment_status = "active_assignment_found"
        elif matching:
            assignment_status = "comment_only"
        else:
            assignment_status = "not_found"
        rows.append({
            "signal": signal,
            "expression": expression,
            "source_ref": dict(mapping.get("source_ref") or {}),
            "internal_member_paths": internal_paths,
            "producer_member_paths": _extract_member_paths(
                " ".join(str(item.get("rhs") or "") for item in active)
            ),
            "producer_function_names": list(dict.fromkeys(producer_functions)),
            "producer_function_refs": producer_function_refs,
            "assignments": matching,
            "primary_assignment": dict(primary_assignment) if isinstance(primary_assignment, Mapping) else {},
            "assignment_status": assignment_status,
        })
    return {
        "schema_version": "arbe-source-output-chain.v1",
        "status": "source_scanned" if probe.get("ok") else "source_scan_partial",
        "assignment_probe": {
            "ok": bool(probe.get("ok")),
            "returncode": probe.get("returncode"),
            "timed_out": probe.get("timed_out"),
        },
        "rows": rows,
        "assignment_count": len(assignments),
        "active_assignment_count": sum(1 for item in assignments if item.get("active") is True),
        "policy": (
            "Lexical source assignments explain the candidate producer path; "
            "they are not proof that this assignment executed at the selected frame."
        ),
    }


def _parse_publication_contract(text: str, *, source_path: str = "") -> dict[str, Any]:
    """Extract source proof for objectlist-before-warning publication order."""
    rows: list[dict[str, Any]] = []
    for raw in str(text or "").splitlines():
        location = re.match(r"^(.*?):([0-9]+):(.*)$", raw)
        if location is None:
            single_file_location = re.match(r"^([0-9]+):(.*)$", raw)
            if single_file_location:
                location = (source_path, single_file_location.group(1), single_file_location.group(2))
        if not location:
            continue
        if isinstance(location, tuple):
            path, line_text, snippet = location
        else:
            path, line_text, snippet = location.groups()
        try:
            line_number = int(line_text)
        except ValueError:
            continue
        rows.append({"path": path, "line": line_number, "snippet": snippet.strip()})

    callback_rows = [
        row for row in rows
        if "corner_radar_post_process_data_callback" in row["snippet"]
    ]
    callback = max(callback_rows, key=lambda row: row["line"]) if callback_rows else None
    warning_publish = next(
        (row for row in rows if "wf_adas_warn_status_with_frame_pub.publish" in row["snippet"]),
        None,
    )
    handler_calls = [
        row for row in rows
        if re.search(r"\bwf_object_display_handler\(\)\s*;", row["snippet"])
    ]
    object_publish_rows = [
        row for row in rows if "wf_objectlist_pub.publish" in row["snippet"]
    ]
    object_publish = max(object_publish_rows, key=lambda row: row["line"]) if object_publish_rows else None
    handler_call = None
    if warning_publish is not None:
        prior = [
            row for row in handler_calls
            if row["path"] == warning_publish["path"] and row["line"] < warning_publish["line"]
        ]
        handler_call = max(prior, key=lambda row: row["line"]) if prior else None
    source_verified = bool(
        callback
        and handler_call
        and warning_publish
        and object_publish
        and handler_call["line"] < warning_publish["line"]
    )
    missing: list[str] = []
    for name, value in (
        ("callback", callback),
        ("objectlist_publish", object_publish),
        ("objectlist_handler_call", handler_call),
        ("warning_with_frame_publish", warning_publish),
    ):
        if value is None:
            missing.append(name)
    return {
        "status": "source_verified" if source_verified else "not_verified",
        "association_mode": "publication_order" if source_verified else "strict",
        "source_file": callback["path"] if callback else (object_publish["path"] if object_publish else ""),
        "callback": callback,
        "objectlist_publish": object_publish,
        "objectlist_handler_call": handler_call,
        "warning_with_frame_publish": warning_publish,
        "missing": missing,
        "preconditions": [
            "capture must preserve per-topic message sequence",
            "objectlist display must be enabled so wf_object_display_handler publishes the message",
            "the same radar's objectlist stream must have exactly one publication between adjacent warning_status_with_frame messages",
        ],
        "basis": (
            "corner_radar_post_process_data_callback calls wf_object_display_handler before "
            "publishing warning_status_with_frame"
            if source_verified
            else "required source publication markers were not all found"
        ),
    }


def _parse_binary_fingerprint(text: str) -> str:
    """Return the first explicit sha256 from a binary identity probe."""
    for line in str(text or "").splitlines():
        match = re.match(r"^\s*([0-9a-fA-F]{64})\s+[* ]?(.+?)\s*$", line)
        if match:
            return match.group(1).lower()
    return ""


class ArbePreflight:
    """Read-only probe for one Linux arbe workspace."""

    def __init__(
        self,
        *,
        runner: CommandRunner,
        server_host: str = "",
        server_user: str = "",
        arbe_root: str,
        algo_source_root: str = "",
        ros_setup: str = "/opt/ros/noetic/setup.bash",
        ros_master_uri: str = "",
        timeout_sec: float = 20.0,
        include_process_snapshot: bool = True,
    ) -> None:
        self.runner = runner
        self.server_host = str(server_host).strip()
        self.server_user = str(server_user).strip()
        self.arbe_root = str(arbe_root).strip()
        self.algo_source_root = (
            str(algo_source_root).strip()
            or _join_remote(self.arbe_root, DEFAULT_ARBE_RELATIVE_ALGO)
        )
        self.ros_setup = str(ros_setup or "").strip()
        self.ros_master_uri = str(ros_master_uri or "").strip()
        self.timeout_sec = max(0.5, float(timeout_sec))
        self.include_process_snapshot = bool(include_process_snapshot)
        self._commands: list[CommandResult] = []

    def _probe(self, name: str, command: str) -> dict[str, Any]:
        result = self.runner.run(command, timeout_sec=self.timeout_sec)
        self._commands.append(result)
        return {
            "name": name,
            "ok": result.ok,
            "returncode": result.returncode,
            "timed_out": result.timed_out,
            "stdout": result.stdout,
            "stderr": result.stderr,
            "duration_sec": round(result.duration_sec, 6),
        }

    def run(self) -> dict[str, Any]:
        if not self.arbe_root:
            return {
                "schema_version": SCHEMA_VERSION,
                "status": "blocked",
                "blockers": ["arbe_root_missing"],
                "warnings": [],
                "commands": [],
            }

        outer = _q(self.arbe_root)
        algo = _q(self.algo_source_root)
        config_path = _join_remote(self.arbe_root, DEFAULT_CONFIG_RELATIVE)
        vis_launch_path = _join_remote(self.arbe_root, DEFAULT_VIS_LAUNCH_RELATIVE)
        para_path = _join_remote(self.arbe_root, DEFAULT_PARA_DEFINE_RELATIVE)
        ros_setup_env = ""
        if self.ros_setup:
            ros_setup_env += f"source {_q(self.ros_setup)} 2>/dev/null || true; "
        ros_setup_env += f"source {_q(_join_remote(self.arbe_root, 'devel/setup.bash'))} 2>/dev/null || true; "
        if self.ros_master_uri:
            ros_setup_env += f"export ROS_MASTER_URI={_q(self.ros_master_uri)}; "

        probes: dict[str, dict[str, Any]] = {}
        probes["outer_root"] = self._probe(
            "outer_root",
            f"test -d {outer} && printf 'directory_present\\n'",
        )
        probes["outer_top_level"] = self._probe(
            "outer_git_top_level",
            f"git -C {outer} rev-parse --show-toplevel",
        )
        probes["outer_head"] = self._probe(
            "outer_git_head",
            f"git -C {outer} rev-parse HEAD",
        )
        probes["outer_branch_status"] = self._probe(
            "outer_git_status",
            f"git -C {outer} status --short --branch",
        )
        probes["submodule_status"] = self._probe(
            "submodule_status",
            f"git -C {outer} submodule status --recursive",
        )
        probes["algo_root"] = self._probe(
            "algo_root",
            f"test -d {algo} && printf 'directory_present\\n'",
        )
        probes["algo_head"] = self._probe(
            "algo_git_head",
            f"git -C {algo} rev-parse HEAD",
        )
        probes["algo_branch_status"] = self._probe(
            "algo_git_status",
            f"git -C {algo} status --short --branch",
        )
        probes["config"] = self._probe(
            "launch_config",
            f"test -f {_q(config_path)} && sed -n '1,240p' {_q(config_path)}",
        )
        probes["vis_launch"] = self._probe(
            "visualization_launch",
            f"test -f {_q(vis_launch_path)} && sed -n '1,140p' {_q(vis_launch_path)}",
        )
        visualization_source_path = _join_remote(
            self.arbe_root,
            "src/arbe_phoenix_radar_driver-master/arbe_gui/src/arbe_visualization_engine/visualization_node.cpp",
        )
        probes["public_source_contract"] = self._probe(
            "public_runtime_source_contract",
            f"test -f {_q(visualization_source_path)} && grep -nE "
            f"'corner_radar_post_process_data_callback|wf_object_display_handler\\(\\)|"
            f"wf_objectlist_pub\\.publish|wf_adas_warn_status_with_frame_pub\\.publish' "
            f"{_q(visualization_source_path)}",
        )
        probes["para_define"] = self._probe(
            "para_define",
            f"test -f {_q(para_path)} && grep -nE "
            f"'^[[:space:]]*#define[[:space:]]+(BUILDMODEL|HILMODEL|"
            f"PF_BUILD_FUNTEST_SGU_INJECTION)' {_q(para_path)}",
        )
        probes["binary_candidates"] = self._probe(
            "binary_candidates",
            f"find {outer} -type f -name arbe_visualization_engine "
            f"2>/dev/null | head -n 80",
        )
        probes["binary_identity"] = self._probe(
            "binary_identity",
            f"find {outer} -type f -name arbe_visualization_engine "
            f"-exec sha256sum {{}} + -exec file {{}} \\; 2>/dev/null | head -n 160",
        )
        probes["gdb"] = self._probe(
            "gdb_capability",
            "command -v gdb 2>/dev/null; "
            "gdb --version 2>/dev/null | head -n 1; "
            "if test -r /proc/sys/kernel/yama/ptrace_scope; then "
            "cat /proc/sys/kernel/yama/ptrace_scope; "
            "else printf 'ptrace_scope=unavailable\\n'; fi",
        )
        if self.include_process_snapshot:
            probes["processes"] = self._probe(
                "visualization_processes",
                "ps -eo pid=,args= 2>/dev/null | "
                "grep '[a]rbe_visualization_engine'",
            )
            probes["ros_nodes"] = self._probe(
                "ros_visualization_nodes",
                f"{ros_setup_env}rosnode list 2>/dev/null | "
                "grep 'arbe_visualization_engine' || true",
            )

        config_text = probes["config"].get("stdout", "")
        para_text = probes["para_define"].get("stdout", "")
        config = _parse_config_values(config_text)
        # The algo source contains many customer variants.  Scan only the
        # active COEM selected by the current launch config, and select the
        # actual Tx mapping/AutoGen source files instead of truncating a
        # recursive grep stream at an arbitrary line count.  This keeps the
        # result source-bound and complete for the selected vehicle while
        # avoiding unrelated variants and test fixtures.
        coem_name = str(config.get("coem_name", "") or "").strip()
        mapping_root = _join_remote(algo, f"coem/{coem_name}") if coem_name else algo
        probes["can_chain"] = self._probe(
            "can_output_chain_scan",
            f"find {_q(mapping_root)} -type f "
            f"\\( -path '*/ASW_ComMapping/RteComMapping*.c' "
            f"-o -path '*/components/com/AutoGen/*.c' "
            f"-o -path '*/components/com/AutoGen/*/*.c' \\) "
            f"-print0 2>/dev/null | xargs -0 -r grep -HnE "
            f"'{_READONLY_SCAN_PATTERN}' 2>/dev/null",
        )
        can_text = probes["can_chain"].get("stdout", "")
        process_text = probes.get("processes", {}).get("stdout", "")
        ros_text = probes.get("ros_nodes", {}).get("stdout", "")

        macros = _parse_macro_values(para_text)
        source_refs = _parse_source_refs(can_text)
        signal_tokens = _parse_signal_tokens(can_text)
        signal_mappings = _parse_signal_mappings(can_text)
        transport_mappings = _parse_transport_mappings(can_text)
        assignment_tokens = {
            token
            for mapping in signal_mappings
            for token in _extract_member_paths(str(mapping.get("expression") or ""))
        }
        assignment_pattern = _member_assignment_pattern(assignment_tokens)
        # The Tx grep above intentionally scans only mapping/transport files.
        # A selected internal value may be produced in a different ASW source
        # file (for example an ADAS state/update module), so perform one
        # additional, still read-only, source scan over the active COEM.  This
        # keeps the output chain current without assuming a fixed feature or
        # file name.
        probes["source_output_assignments"] = self._probe(
            "source_output_internal_assignments",
            f"find {_q(mapping_root)} -type f "
            f"\\( -name '*.c' -o -name '*.h' -o -name '*.cc' -o -name '*.cpp' \\) "
            f"-print0 2>/dev/null | xargs -0 -r grep -HnE "
            f"'{assignment_pattern}' 2>/dev/null | head -n 6000",
        ) if signal_mappings else {
            "name": "source_output_internal_assignments",
            "ok": False,
            "returncode": 0,
            "timed_out": False,
            "stdout": "",
            "stderr": "no_write_mappings",
            "duration_sec": 0.0,
        }
        assignment_probe = probes["source_output_assignments"]
        assignment_rows = _parse_member_assignments(
            assignment_probe.get("stdout", ""),
            selected_tokens=assignment_tokens,
        )
        function_names = {
            name
            for row in assignment_rows
            if row.get("active") is True
            for name in _extract_function_calls(str(row.get("rhs") or ""))
        }
        function_pattern = (
            "(^|[^A-Za-z0-9_])(" + "|".join(
                re.escape(name) for name in sorted(function_names, key=len, reverse=True)
            ) + ")[[:space:]]*\\("
            if function_names else "a^"
        )
        probes["source_output_functions"] = self._probe(
            "source_output_producer_functions",
            f"find {_q(mapping_root)} -type f "
            f"\\( -name '*.c' -o -name '*.h' -o -name '*.cc' -o -name '*.cpp' \\) "
            f"-print0 2>/dev/null | xargs -0 -r grep -HnE "
            f"'{function_pattern}' "
            f"2>/dev/null | head -n 2000",
        ) if function_names else {
            "name": "source_output_producer_functions",
            "ok": False,
            "returncode": 0,
            "timed_out": False,
            "stdout": "",
            "stderr": "no_producer_functions",
            "duration_sec": 0.0,
        }
        function_probe = probes["source_output_functions"]
        source_output_chain = _build_source_output_chain(
            signal_mappings,
            assignment_rows,
            function_refs=_parse_function_refs(function_probe.get("stdout", ""), names=function_names),
            probe=assignment_probe,
        )
        public_contract = _parse_publication_contract(
            probes["public_source_contract"].get("stdout", ""),
            source_path=visualization_source_path,
        )
        processes = _parse_processes(process_text)
        ros_nodes = [line.strip() for line in ros_text.splitlines() if line.strip()]
        binaries = [
            line.strip()
            for line in probes["binary_candidates"].get("stdout", "").splitlines()
            if line.strip()
        ]
        binary_identity_text = probes["binary_identity"].get("stdout", "")
        binary_fingerprint = _parse_binary_fingerprint(binary_identity_text)

        blockers: list[str] = []
        warnings: list[str] = []
        for name in (
            "outer_root",
            "outer_top_level",
            "outer_head",
            "algo_root",
            "algo_head",
            "config",
            "para_define",
        ):
            if not probes[name].get("ok", False):
                blockers.append(f"{name}_unavailable")

        hilmodel = macros.get("HILMODEL", "")
        if hilmodel and hilmodel != "2":
            warnings.append(f"hilmodel_not_2:{hilmodel}")
        if not hilmodel:
            warnings.append("hilmodel_not_found")

        gdb_text = probes["gdb"].get("stdout", "")
        gdb_lines = [line.strip() for line in gdb_text.splitlines() if line.strip()]
        gdb_path = next(
            (line for line in gdb_lines if line.endswith("/gdb")),
            "",
        )
        gdb_version = next(
            (
                line
                for line in gdb_lines
                if re.search(r"(?:^|[ (])gdb(?:[ )]|$)", line, flags=re.IGNORECASE)
                and not line.endswith("/gdb")
            ),
            "",
        )
        ptrace_scope = next(
            (line for line in reversed(gdb_lines) if re.fullmatch(r"[0-3]", line)),
            "",
        )
        gdb_available = bool(gdb_version)
        if not gdb_available:
            warnings.append("gdb_not_found")

        can_observation_status = "candidate_source_found" if source_refs else "not_found"
        runtime_status = "ready" if processes else "not_running"
        if not binaries:
            warnings.append("arbe_visualization_engine_binary_not_found")

        status = "blocked" if blockers else ("ready" if runtime_status == "ready" else "partial")
        return {
            "schema_version": SCHEMA_VERSION,
            "status": status,
            "server": {
                "host": self.server_host,
                "user": self.server_user,
                "transport": "ssh" if self.server_host else "local",
            },
            "workspace": {
                "arbe_root": self.arbe_root,
                "algo_source_root": self.algo_source_root,
                "outer": {
                    "head": _stdout_line(probes["outer_head"]),
                    "status": probes["outer_branch_status"].get("stdout", ""),
                    "status_ok": probes["outer_branch_status"].get("ok", False),
                },
                "algo_source": {
                    "head": _stdout_line(probes["algo_head"]),
                    "status": probes["algo_branch_status"].get("stdout", ""),
                    "status_ok": probes["algo_branch_status"].get("ok", False),
                },
                "submodule_status": probes["submodule_status"].get("stdout", ""),
            },
            "configuration": {
                "config_path": config_path,
                "visualization_launch_path": vis_launch_path,
                "resolved": config,
                "raw_config_available": bool(config_text),
            },
            "build": {
                "para_define_path": para_path,
                "macros": macros,
                "binary_candidates": binaries,
                "binary_count": len(binaries),
                "binary_fingerprint": binary_fingerprint,
                "binary_identity_probe": binary_identity_text,
            },
            "runtime": {
                "status": runtime_status,
                "ros_setup": self.ros_setup,
                "ros_master_uri": self.ros_master_uri,
                "processes": processes,
                "ros_nodes": ros_nodes,
                "expected_process_pattern": (
                    "/radar<id>_visualization_engine/"
                    "arbe_visualization_engine"
                ),
                "bash_start_required": True,
            },
            "gdb": {
                "available": gdb_available,
                "path": gdb_path,
                "version": gdb_version,
                "ptrace_scope": ptrace_scope or "unavailable",
                "raw_probe": gdb_text,
                "attach_mode": "existing_pid_after_bash_start",
                "launch_under_gdb": "fallback_only",
            },
            "can_output": {
                "observation_status": can_observation_status,
                "source_scope": mapping_root,
                "candidate_signal_tokens": signal_tokens,
                "write_mappings": signal_mappings,
                "transport_mappings": transport_mappings,
                "source_output_chain": source_output_chain,
                "source_refs": source_refs,
                "runtime_observed": False,
                "note": (
                    "Source candidates are not runtime CAN Tx evidence; "
                    "GDB/bridge must observe execution."
                ),
            },
            "public_evidence": {
                "objectlist_frame_contract": public_contract,
                "source_ref": {
                    "path": _join_remote(
                        self.arbe_root,
                        "src/arbe_phoenix_radar_driver-master/arbe_gui/src/arbe_visualization_engine/visualization_node.cpp",
                    ),
                },
            },
            "probes": probes,
            "blockers": blockers,
            "warnings": warnings,
            "commands": [item.to_dict() for item in self._commands],
        }


def _stdout_line(probe: dict[str, Any]) -> str:
    text = str(probe.get("stdout", "")).strip()
    return text.splitlines()[0] if text else ""


__all__ = [
    "SCHEMA_VERSION",
    "ArbePreflight",
    "CommandResult",
    "CommandRunner",
    "LocalShellRunner",
    "SshCommandRunner",
]
